import type { Metadata } from "next";
import { Kanit,Nunito } from "next/font/google";
import "./globals.css";

const NunitoSans = Nunito({
  variable: "--font-sans",
  subsets: ["latin"],
});

const KanitMono = Kanit({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["600","500"]
});

export const metadata: Metadata = {
  title: "Alberto D. Basabe Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${NunitoSans.variable} ${KanitMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
